spring:
  application:
    name: reactor-pets
  datasource:
    url: jdbc:h2:mem:petdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

axon:
  axonserver:
    servers: localhost:8124
  eventhandling:
    processors:
      pet-status:
        mode: tracking
        source: eventBus
        batch-size: 10
      pet-statistics:
        mode: tracking
        source: eventBus
        batch-size: 10

logging:
  level:
    org.axonframework: INFO
    com.reactor.pets: DEBUG
